# language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t nuinattapon/docker-frontend .
script:
  - docker run -e CI=true nuinattapon/docker-frontend npm run test
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script: docker push nuinattapon/test
  on:
    branch: master
