# language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t nuinattapon/docker-frontend .
script:
  - docker run -e CI=true nuinattapon/docker-frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-frontend"
  env: "DockerFrontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-462890615219"
  bucket_path: "docker-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
