# language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t "$DOCKER_USERNAME"/docker-frontend .
script:
  - docker run -e CI=true "$DOCKER_USERNAME"/docker-frontend npm run test
before_deploy:
  - docker build -f Dockerfile -t "$DOCKER_USERNAME"/docker-frontend .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_USERNAME"/docker-frontend
deploy:
  provider: script
  script: docker push "$DOCKER_USERNAME"/docker-frontend
  on:
    branch: master
